[build]
  publish = "."
  functions = "netlify/functions"
  
[dev]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Explicitní povolení CORS pro funkce
[[headers]]
  for = "/.netlify/functions/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[template.environment]
  ADMIN_EMAIL = "honzamazoch@email.cz"
