[build]
  publish = "."
  functions = "netlify/functions"  # Choose one primary location
  
[dev]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"  # Make this the single source
  node_bundler = "esbuild"

[template.environment]
  ADMIN_EMAIL = "honzamazoch@email.cz"
