functionsDirectory = "C:\\Users\\mazoc\\Downloads\\web_last\\web\\cycling-gallery\\functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "C:\\Users\\mazoc\\Downloads\\web_last\\web\\cycling-gallery"
publishOrigin = "config"
functions = "C:\\Users\\mazoc\\Downloads\\web_last\\web\\cycling-gallery\\functions"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[dev]
functions = "functions"

[template]

  [template.environment]
  ADMIN_EMAIL = "honzamazoch@email.cz"

[functions]

  [functions."*"]
  node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]